import { ModelPricing } from '../types';

export const INITIAL_MODELS: ModelPricing[] = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    tier: 'FRONTIER',
    promptPricePerM: 15.00,
    completionPricePerM: 60.00,
    latencyAvgMs: 820,
    qualityScore: 96,
    bestFor: ['COMPLEX', 'CODE', 'REASONING'],
    active: true,
    color: '#ffba20', // secondary gold
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    tier: 'FRONTIER',
    promptPricePerM: 12.00,
    completionPricePerM: 48.00,
    latencyAvgMs: 780,
    qualityScore: 95,
    bestFor: ['COMPLEX', 'CODE', 'CREATIVE'],
    active: true,
    color: '#abc7ff', // tertiary cyan
  },
  {
    id: 'mixtral-8x7b',
    name: 'Mixtral-8x7B',
    provider: 'Mistral AI',
    tier: 'MID',
    promptPricePerM: 0.60,
    completionPricePerM: 0.60,
    latencyAvgMs: 340,
    qualityScore: 82,
    bestFor: ['REASONING', 'EXTRACTION', 'CREATIVE'],
    active: true,
    color: '#00e639', // primary green
  },
  {
    id: 'gemini-flash',
    name: 'Gemini 3.7 Flash',
    provider: 'Google Cloud',
    tier: 'MID',
    promptPricePerM: 0.35,
    completionPricePerM: 1.05,
    latencyAvgMs: 210,
    qualityScore: 88,
    bestFor: ['EXTRACTION', 'REASONING', 'SIMPLE'],
    active: true,
    color: '#72ff70', // light neon green
  },
  {
    id: 'llama-3-8b',
    name: 'Llama-3-8B',
    provider: 'Meta / Groq',
    tier: 'ULTRA_CHEAP',
    promptPricePerM: 0.15,
    completionPricePerM: 0.15,
    latencyAvgMs: 95,
    qualityScore: 74,
    bestFor: ['SIMPLE', 'EXTRACTION'],
    active: true,
    color: '#00ff41', // bright neon green
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek-V3',
    provider: 'DeepSeek',
    tier: 'MID',
    promptPricePerM: 0.27,
    completionPricePerM: 1.10,
    latencyAvgMs: 310,
    qualityScore: 91,
    bestFor: ['CODE', 'REASONING', 'EXTRACTION'],
    active: true,
    color: '#00e5ff',
  },
  {
    id: 'qwen-2.5-72b',
    name: 'Qwen 2.5 72B',
    provider: 'Alibaba Cloud (Qwen API)',
    tier: 'MID',
    promptPricePerM: 0.35,
    completionPricePerM: 1.20,
    latencyAvgMs: 340,
    qualityScore: 93,
    bestFor: ['CODE', 'REASONING', 'COMPLEX'],
    active: true,
    color: '#00C9E8',
  },
  {
    id: 'qwen-2.5-coder-32b',
    name: 'Qwen 2.5 Coder',
    provider: 'Alibaba Cloud (Qwen API)',
    tier: 'MID',
    promptPricePerM: 0.20,
    completionPricePerM: 0.60,
    latencyAvgMs: 250,
    qualityScore: 92,
    bestFor: ['CODE', 'EXTRACTION'],
    active: true,
    color: '#38efff',
  }
];

export const FRONTIER_BASELINE_ID = 'gpt-4o';
